default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: db
  port: 5432

development:
  <<: *default
  database: scraping_service_development

test:
  <<: *default
  database: scraping_service_test

production:
  <<: *default
  database: scraping_service_production
  username: scraping_service_user
  password: <%= ENV['SCRAPING_SERVICE_DATABASE_PASSWORD'] %>
